# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where_from', models.CharField(max_length=50)),
                ('where_to', models.CharField(max_length=50)),
                ('date_leaving', models.CharField(max_length=20)),
                ('type_of_ticket', models.CharField(choices=[('ONE', 'Oneway'), ('TWO', 'Twoway')], default='ONE', max_length=3)),
                ('travelling_persons', models.ImageField(default=1, upload_to=b'')),
                ('kids', models.IntegerField(default=0)),
            ],
        ),
    ]
