# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20170725_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='class_of_choice',
            field=models.CharField(choices=[('Business', 'Business'), ('Economy', 'Economy')], default='Economy', max_length=30),
        ),
    ]
