# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20170726_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='kids',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
